language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - cd frontend
  - npm i react
  - CI=false npm run build
  - CI=true npm run test:ci -- --forceExit --detectOpenHandles --maxWorkers=10
